### ISSUE TITLE
pip install error inconsistent version of elasticsearch-dsl

### ISSUE THREAD

**Issue by AlexGKim** [TOMToolkit/tom_antares#23] opened 2021-08-11 16:11 UTC
In making a Docker image of my TOM Toolkit, the inclusion of
`tom-antares`
in
`requirements.txt`
leads to an 

```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 366, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 226, in _attempt_to_pin_criterion
    raise InconsistentCandidate(candidate, criterion)
pip._vendor.resolvelib.resolvers.InconsistentCandidate: Provided candidate LinkCandidate('https://files.pythonhosted.org/packages/12/1e/c59c873cc63643b277e80efec0c5a9714798e4716ca43e97fba35b94e811/elasticsearch_dsl-7.4.0-py2.py3-none-any.whl#sha256=046ea10820b94c075081b528b4526c5bc776bda4226d702f269a5f203232064b (from https://pypi.org/simple/elasticsearch-dsl/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*)') does not satisfy SpecifierRequirement('elasticsearch-dsl~=7.3'), SpecifierRequirement('elasticsearch-dsl~=7.3.0')
```

Earlier `elasticsearch-dsl` is installed with a later version

```
Collecting elasticsearch-dsl~=7.3
  Downloading elasticsearch_dsl-7.4.0-py2.py3-none-any.whl (63 kB)
```

**Comment by dmcollom** [comment] 2021-08-11 17:17
I'm unable to reproduce this with an almost identical Dockerfile. Can you put your requirements file in here as well?

**Comment by AlexGKim** [comment] 2021-08-11 17:21
These requirements were copied from `tom-demo`

```
django-cors-headers>=3.7
factory_boy==2.12.0
gunicorn[gevent]==20.0.4
psycopg2===2.8.4
tom-alerts-dash[scimma]>=0.1.2
tom-superevents>=0.1
django-webpack-loader==0.6.0
tomtoolkit>=2.6.5
whitenoise~=5.2
tom-fink
tom-antares
```

**Comment by dmcollom** [comment] 2021-08-11 17:22
And this is happening on the build step? Mine is only installing 7.3, which is the requirement for both `tom-fink` and `tom-antares`.

**Comment by AlexGKim** [comment] 2021-08-11 17:28
Yes, the error occurs in the Docker build step.  No errors occur from my desktop deployment.

**Comment by dmcollom** [comment] 2021-08-11 17:53
Ah, managed to reproduce this once I had both `tom-fink` and `tom-antares`. This is a weird one...both libraries have the requirement `elasticsearch-dsl~=7.3`.

If you want to just get past this immediately, then believe it or not, but swapping the order of the two in the requirements fixes the issue (`tom-antares` has to be first). I will work through the dependency resolution issues in the meantime, for which I have a few suspicions.

**Comment by AlexGKim** [comment] 2021-08-11 17:55
Thanks for figuring this out!

Does it have to do with the number of decimals?  7.3 vs 7.3.0?

**Comment by dmcollom** [comment] 2021-08-11 19:47
Yes, turns out I've perpetually misunderstood the `~` and somehow never been bitten by it previously. I'll have to modify the requirements in `tom-fink`.

**Comment by dmcollom** [comment] 2021-08-12 22:46
This is now fixed in the `tom-fink` project.

**Closed by dmcollom** 2021-08-12 22:46 UTC
